name: Unit tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  greet-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Greeting
        run: echo "Hello, ${{ github.event.inputs.who-to-greet || 'World' }}!"
        shell: bash

      - name: Random Number Generator
        id: random-number-generator
        run: echo "::set-output name=random-number::$RANDOM"
        shell: bash

      - name: Set GitHub Path
        run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        shell: bash
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}

      - name: Make goodbye.sh Executable
        run: chmod +x goodbye.sh

      - name: Run goodbye.sh
        run: ./goodbye.sh
